### ISSUE TITLE
Multi target framework needed

### ISSUE THREAD

**Issue by Nordes** [hnx8/ReadJEnc#2]
As the title says,

have multiple framework target on the nuget package.

By example: netcoreapp2.0;netstandard2.0;net20;net35;net40;net45;net46;net461

**Comment by hnx8** [comment]
(2018/4/21 updated)
Hi, Nordes, 

(1)About pull-request
 I installed VisualStudio 2017 and got confirmation. Merged.
 Thank you very much. "Readme_en.md" is also very helpful. 
 (And please note I adjusted a bit about small details(folder name and so on)).

(2)About NuGet Gallery
 Old version [https://www.nuget.org/packages/ReadJEnc/] , I could hide it 
 by Making the package into 「Unlisted Package」.
 It can be displayed by entering URL direct, but it is not displayed 
 in NuGet-Gallery search.

<del>
 I'm also not used to registering packages with NuGet.
 I would like to have your registered [https://www.nuget.org/packages/Hnx8.ReadJEnc/] 
 as official version, if possible.
 so, I also rewritten the NuGet URL pointed to by "readme.md".
</del>

->2018/04/21  I released fixed-nupkg(v1.3.1.1) to [https://www.nuget.org/packages/ReadJEnc] successfully. Please do not mention the above deleted description. Also, On the package management screen of NuGet[Hnx8.ReadJenc], click Status"Listed", and uncheck "List Hnx8.ReadJEnc (1.3.1) in search results", It has similar effect to package deletion.
And, I also added you to the original ReadJEnc co-owner. If you find problems with my release, you can update the NuGet gallery directly.

(3)About the harm of [Description]Attribute
 I did not recognize it is not available in NET4.6.2 etc. therefore it is impossible to include as a target.
 I am planning to fix this so that I will not use DescriptionAttribute in a few days to a week (or weeks...?).
->2018/04/21  I fixed, and released above.

Thanks.

**Comment by Nordes** [comment]
Sorry for late reply ;).  Thank you for merging the request.

Perfect, I'll keep you in touch if I find any issue.

(Updated to not have the package listed anymore)

**Comment by hnx8** [comment]
I re-fixed it because I forgot to add it to .NET Core 1.0 / 1.1.... 
With This, it is really terminate.
